#!/usr/bin/perl

my $uae_host = "uae.ucweb.local";

use Getopt::Long;

print "upload2newuae starting...\n";
print "usage: -pkg_path <pkg_path> -app_id <app_id>\n";

my ($pkg_path, $app_id);

GetOptions(
   'pkg_path=s' => \$pkg_path, #程序包所在路径
   'app_id=s'   => \$app_id    #在uae中定义的App ID
);

my $upload_file_name = `ls -t $pkg_path | head -1`;
$upload_file_name =~ s/\n//g;

my $curl_cmd="curl --user uae_system\@126.com:eJr2pUDT5AnzYTKl -F 'git_info=$ENV{'PAYLOAD'}' -F \"files[]=\@$pkg_path/$upload_file_name\" http://uae.ucweb.local/$app_id/upload.json";
print "$curl_cmd\n";
`$curl_cmd`;
