# 不要修改该文件, 会自动生成, 详见 http://gitlab.alibaba-inc.com/node/ci

cache:
  untracked: true
  paths:
    - node_modules/

before_script:
  - source $HOME/.nvm/nvm.sh
  - echo $PATH
  - shopt -s expand_aliases
  - alias npm5='npm --registry=http://registry.npm.alibaba-inc.com'
  - node -v && npm5 -v
node-8:
  only:
    - /^release/
    - tags

  # image: reg.docker.alibaba-inc.com/dockerlab/node-ci:1.0.0
  script:
    # - tnpm i --install-node=6 --no-cache
    # - time tnpm run ci
    # 上传 UAE
    - V_UAE_ID="5977"
    - V_OUT_PATH="$CI_PROJECT_DIR/out" # 临时目标
    - V_RELEASE_PATH="$CI_PROJECT_DIR/releases" # 打包目录

    # 打包文件名
    - V_PACK_TIME=`date "+%Y%m%d%H%M"`
    - V_PACK_NAME="${CI_PROJECT_DIR##*/}-$CI_BUILD_REF_NAME-$V_PACK_TIME-bin.tgz"

    - mkdir -p $V_RELEASE_PATH

    # 安装依赖，构建
    - npm5 i
    - npm5 run build
    - cd out && npm5 i --production && cd ..

    # 打包
    - cd $V_OUT_PATH
    - tar -czf $V_RELEASE_PATH/$V_PACK_NAME *
    - cd $CI_PROJECT_DIR
    - ./builder/script/upload2newuae -pkg_path $V_RELEASE_PATH -app_id $V_UAE_ID

    # 查看包
    - ls $V_RELEASE_PATH
    - ls $V_OUT_PATH
